ci:
    autofix_commit_msg: 'style: pre-commit auto fixes'
    autofix_prs: true

repos:
-   repo: https://github.com/sirosen/check-jsonschema
    rev: 0.28.4
    hooks:
    -   id: check-github-workflows
