name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions/setup-python@f38219332975fe8f9c04cca981d674bf22aea1d3
        with:
          python-version: 3.7
      - name: Get version
        id: addon_version
        run: |
          VERSION=$(cat package/default/app.conf | grep -e ^version | awk '{print $3}')
          echo "::set-output name=VERSION::$VERSION"
      - name: Get addon name
        id: addon_name
        run: |
          ADDON_NAME=$(cat package/default/app.conf | grep -e ^id | awk '{print $3}')
          echo "::set-output name=ADDON_NAME::$ADDON_NAME"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade splunk-packaging-toolkit splunk-add-on-ucc-framework
      - name: Building app
        run: |
          ucc-gen --ta-version ${{ steps.addon_version.outputs.VERSION }}
      - name: Packaging app
        run: |
          mkdir dist
          slim package output/${{ steps.addon_name.outputs.ADDON_NAME }} -o dist/
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2
        with:
          name: ${{ steps.addon_name.outputs.ADDON_NAME }}-${{
            steps.addon_version.outputs.VERSION }}.tar.gz
          path: dist/${{ steps.addon_name.outputs.ADDON_NAME }}-${{
            steps.addon_version.outputs.VERSION }}.tar.gz
