name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.7
      - name: Get version
        id: addon_version
        run: |
          VERSION=$(cat package/default/app.conf | grep -e ^version | awk '{print $3}')
          echo "::set-output name=VERSION::$VERSION"
      - name: Get addon name
        id: addon_name
        run: |
          ADDON_NAME=$(cat package/default/app.conf | grep -e ^id | awk '{print $3}')
          echo "::set-output name=ADDON_NAME::$ADDON_NAME"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade splunk-packaging-toolkit==1.0.1 splunk-add-on-ucc-framework==5.10.1
      - name: Building app
        run: |
          ucc-gen --ta-version ${{ steps.addon_version.outputs.VERSION }}
      - name: Packaging app
        run: |
          mkdir dist
          slim package output/${{ steps.addon_name.outputs.ADDON_NAME }} -o dist/
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{ steps.addon_name.outputs.ADDON_NAME }}-${{steps.addon_version.outputs.VERSION }}.tar.gz
          path: dist/${{ steps.addon_name.outputs.ADDON_NAME }}-${{steps.addon_version.outputs.VERSION }}.tar.gz
      - uses: splunk/appinspect-cli-action@v1.4.7
        with:
          app_path: dist/${{ steps.addon_name.outputs.ADDON_NAME }}-${{steps.addon_version.outputs.VERSION }}.tar.gz
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: appinspect_result.json
          path: appinspect_result.json
